### ISSUE TITLE
Invalid interface "mocha-gherkin"

### ISSUE THREAD

**Issue by Cordazar** [jgkim/mocha-gherkin#2]
node 0.12.8
mocha-gherkin 0.1.14
mocha 2.3.4

```
/Users/someuser/someproject/node_modules/mocha/lib/mocha.js:197
      throw new Error('invalid interface "' + name + '"');
            ^
Error: invalid interface "mocha-gherkin"
    at Mocha.ui (/Users/someuser/someproject/node_modules/mocha/lib/mocha.js:197:13)
    at Object.<anonymous> (/Users/someuser/someproject/node_modules/mocha/bin/_mocha:206:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jgkim** [comment]
@Cordazar Thank you for spotting this bug. This is due to the missing dependency, i.e. `source-map-support`. I am fixing this and publish `0.1.15`.
